sources:
  - name: dlt_raw
    schema: marketplace_andes_analytics_raw
    tables:
      - name: users
      - name: user_profiles
      - name: listings
      - name: listing_status_history
      - name: user_listing_interaction