services:
  server:
    build:
      context: .
      dockerfile: images/Dockerfile.server
    env_file:
      - .env.server
    restart: always
    ports:
      - 8000:8000
    depends_on:
      migration:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml

  migration:
    build:
      context: .
      dockerfile: images/Dockerfile.migrations
    env_file:
      - .env.migrations
    restart: no
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:18.3-trixie
    restart: always
    user: postgres
    env_file:
      - .env.pg
    volumes:
      - ./util/pg:/docker-entrypoint-initdb.d:ro,Z
      - postgres-data:/var/lib/postgresql
    ports:
      - 5432:5432
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:9.13
    restart: always
    env_file:
      - .env.pgadmin
    profiles:
      - pgadmin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./util/pgadmin/servers.compose.json:/pgadmin4/servers.json:ro,Z
    ports:
      - 5050:80
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres-data:
  pgadmin-data:
