services:
  server:
    build:
      context: .
    env_file:
      - .env
    restart: always
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml

  db:
    image: postgres:18.3-trixie
    restart: always
    user: postgres
    secrets:
      - pg-admin-password
      - pg-backend-password
    volumes:
      - ./scripts/pg:/docker-entrypoint-initdb.d:ro,Z
      - db-data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg-admin-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:9.13
    restart: always
    profiles:
      - db-admin
    secrets:
      - pgadmin-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/pgadmin-password
    ports:
      - 5050:80
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
  pgadmin-data:


secrets:
  pg-admin-password:
    environment: PG_ADMIN_PASSWORD
  pg-backend-password:
    environment: PG_BACKEND_PASSWORD
  pgadmin-password:
    environment: PGADMIN_DEFAULT_PASSWORD
